export SHELL=/mnt/SDCARD/App/zsh/
export PROMPT='%n@%m %~ %# '
export sysdir=/mnt/SDCARD/.tmp_update
export miyoodir=/mnt/SDCARD/miyoo
export LD_LIBRARY_PATH="/mnt/SDCARD/App/zsh/lib:/lib:/config/lib:$miyoodir/lib:$sysdir/lib:$sysdir/lib/parasyte"
export PATH="$sysdir/bin:$PATH"
export ZDOTDIR="/mnt/SDCARD/App/zsh/share/zsh"
export ZSH_CACHE_DIR="/mnt/SDCARD/App/zsh/share/zsh"
export TERMINFO="/mnt/SDCARD/App/zsh/share/terminfo"
export TERM="vt102"